# Generated by Django 5.0.6 on 2025-10-01 18:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created_at'], 'verbose_name': 'مدرّس', 'verbose_name_plural': 'مدرّسون'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_salary_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر دفعة راتب'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'إداري'), ('accountant', 'محاسب'), ('mentor', 'مرشد'), ('manager', 'مدير'), ('marketing', 'تسويق'), ('reception', 'استقبال')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branches',
            field=models.CharField(help_text='الفروع التي يدرّسها المدرّس مفصولة بفاصلة', max_length=100, verbose_name='الفروع'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='الأجر عن كل حصة دراسية', max_digits=10, null=True, verbose_name='أجر الساعة'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='يستخدم مع نوع الراتب الشهري أو المختلط', max_digits=10, null=True, verbose_name='راتب شهري ثابت'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary_type',
            field=models.CharField(choices=[('hourly', 'ساعي'), ('monthly', 'شهري ثابت'), ('mixed', 'مختلط (شهري + ساعي)')], default='hourly', max_length=20, verbose_name='نوع الراتب'),
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('students_view', 'عرض الطلاب / View Students'), ('students_create', 'إضافة طالب / Add Student'), ('students_edit', 'تعديل الطلاب / Edit Students'), ('students_delete', 'حذف الطلاب / Delete Students'), ('students_receipt', 'إيصالات الطلاب / Student Receipts'), ('teachers_view', 'عرض المدرسين / View Teachers'), ('teachers_create', 'إضافة مدرس / Add Teacher'), ('teachers_edit', 'تعديل المدرسين / Edit Teachers'), ('teachers_delete', 'حذف المدرسين / Delete Teachers'), ('teachers_salary', 'رواتب المدرسين / Teacher Salaries'), ('attendance_view', 'عرض الحضور / View Attendance'), ('attendance_take', 'تسجيل الحضور / Take Attendance'), ('attendance_edit', 'تعديل الحضور / Edit Attendance'), ('attendance_export', 'تصدير الحضور / Export Attendance'), ('classroom_view', 'عرض الشعب / View Classrooms'), ('classroom_create', 'إنشاء شعبة / Create Classroom'), ('classroom_edit', 'تعديل الشعب / Edit Classrooms'), ('classroom_delete', 'حذف الشعب / Delete Classrooms'), ('classroom_assign', 'تعيين الطلاب / Assign Students'), ('grades_view', 'عرض العلامات / View Grades'), ('grades_edit', 'تعديل العلامات / Edit Grades'), ('grades_export', 'تصدير العلامات / Export Grades'), ('grades_print', 'طباعة العلامات / Print Grades'), ('courses_view', 'عرض المواد / View Subjects'), ('courses_create', 'إضافة مادة / Add Subject'), ('courses_edit', 'تعديل المواد / Edit Subjects'), ('courses_delete', 'حذف المواد / Delete Subjects'), ('accounting_view', 'عرض المحاسبة / View Accounting'), ('accounting_entries', 'قيود اليومية / Journal Entries'), ('accounting_accounts', 'دليل الحسابات / Chart of Accounts'), ('accounting_reports', 'التقارير المالية / Financial Reports'), ('accounting_receipts', 'إيصالات الطلاب / Student Receipts'), ('accounting_expenses', 'المصروفات / Expenses'), ('accounting_budgets', 'الميزانيات / Budgets'), ('hr_view', 'عرض الموظفين / View Employees'), ('hr_create', 'إضافة موظف / Add Employee'), ('hr_edit', 'تعديل الموظفين / Edit Employees'), ('hr_delete', 'حذف الموظفين / Delete Employees'), ('hr_salary', 'رواتب الموظفين / Employee Salaries'), ('hr_advances', 'سلف الموظفين / Employee Advances'), ('hr_vacations', 'إجازات الموظفين / Employee Vacations'), ('admin_dashboard', 'لوحة التحكم / Dashboard'), ('admin_settings', 'إعدادات النظام / System Settings'), ('admin_users', 'إدارة المستخدمين / User Management'), ('admin_backup', 'النسخ الاحتياطي / Backup'), ('reports_students', 'تقارير الطلاب / Student Reports'), ('reports_teachers', 'تقارير المدرسين / Teacher Reports'), ('reports_financial', 'التقارير المالية / Financial Reports'), ('reports_attendance', 'تقارير الحضور / Attendance Reports')], max_length=50)),
                ('is_granted', models.BooleanField(default=False, verbose_name='مُمنوح / Granted')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='employ.employee')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مُنح بواسطة / Granted By')),
            ],
            options={
                'verbose_name': 'صلاحية الموظف / Employee Permission',
                'verbose_name_plural': 'صلاحيات الموظفين / Employee Permissions',
                'unique_together': {('employee', 'permission')},
            },
        ),
    ]
