# Generated by Django 5.0.6 on 2025-10-04 04:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0004_remove_employee_hire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeepermission',
            options={'verbose_name': 'صلاحية موظف', 'verbose_name_plural': 'صلاحيات الموظفين'},
        ),
        migrations.RemoveField(
            model_name='employeepermission',
            name='last_salary_payment_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'مسؤول'), ('accountant', 'محاسب'), ('hr', 'موارد بشرية'), ('staff', 'موظف')], default='staff', max_length=50, verbose_name='الوظيفة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='راتب شهري'),
        ),
        migrations.AlterField(
            model_name='employeepermission',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنح'),
        ),
        migrations.AlterField(
            model_name='employeepermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مُنح بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeepermission',
            name='is_granted',
            field=models.BooleanField(default=False, verbose_name='ممنوح'),
        ),
    ]
