# Generated by Django 5.2.3 on 2025-01-15 12:00

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_options_alter_accountingperiod_options_and_more'),
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ / Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ / Amount')),
                ('purpose', models.CharField(max_length=500, verbose_name='الغرض / Purpose')),
                ('is_repaid', models.BooleanField(default=False, verbose_name='مسدد / Repaid')),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المسدد / Repaid Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة / Created By')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_advances', to='accounts.journalentry', verbose_name='قيد اليومية / Journal Entry')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='employ.teacher', verbose_name='المعلم / Teacher')),
            ],
            options={
                'verbose_name': 'سلفة المعلم / Teacher Advance',
                'verbose_name_plural': 'سلف المعلمين / Teacher Advances',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(
                choices=[
                    ('MANUAL', 'يدوي / Manual'),
                    ('enrollment', 'تسجيل / enrollment'),
                    ('PAYMENT', 'دفع / Payment'),
                    ('COMPLETION', 'إكمال / Completion'),
                    ('EXPENSE', 'مصروف / Expense'),
                    ('SALARY', 'راتب / Salary'),
                    ('ADVANCE', 'سلفة / Advance'),
                    ('ADJUSTMENT', 'تسوية / Adjustment'),
                ],
                default='MANUAL',
                max_length=20,
                verbose_name='نوع القيد / Entry Type'
            ),
        ),
    ]