# Generated by Django 5.0.6 on 2025-10-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fix_financial_operations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'الحساب / Account', 'verbose_name_plural': 'الحسابات / Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'الفترة المحاسبية / Accounting Period', 'verbose_name_plural': 'الفترات المحاسبية / Accounting Periods'},
        ),
        migrations.AlterModelOptions(
            name='discountrule',
            options={'ordering': ['reason'], 'verbose_name': 'قاعدة الخصم / Discount Rule', 'verbose_name_plural': 'قواعد الخصم / Discount Rules'},
        ),
        migrations.AlterModelOptions(
            name='studentaccountlink',
            options={'verbose_name': 'ربط حساب الطالب / Student Account Link', 'verbose_name_plural': 'روابط حسابات الطلاب / Student Account Links'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'الأصول / Assets'), ('LIABILITY', 'الخصوم / Liabilities'), ('EQUITY', 'حقوق الملكية / Equity'), ('REVENUE', 'الإيرادات / Revenue'), ('EXPENSE', 'المصروفات / Expenses')], max_length=20, verbose_name='نوع الحساب / Account Type'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('SALARY', 'راتب / Salary'), ('TEACHER_SALARY', 'راتب مدرس / Teacher Salary'), ('RENT', 'إيجار / Rent'), ('UTILITIES', 'مرافق / Utilities'), ('SUPPLIES', 'مستلزمات / Supplies'), ('MARKETING', 'تسويق / Marketing'), ('MAINTENANCE', 'صيانة / Maintenance'), ('OTHER', 'أخرى / Other')], max_length=20, verbose_name='الفئة / Category'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد / Cash'), ('BANK', 'بنك / Bank'), ('CARD', 'بطاقة / Card'), ('TRANSFER', 'تحويل / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد / Cash'), ('BANK', 'بنك / Bank'), ('CARD', 'بطاقة / Card'), ('TRANSFER', 'تحويل / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
        migrations.AlterField(
            model_name='studentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقد / Cash'), ('BANK', 'بنك / Bank'), ('CARD', 'بطاقة / Card'), ('TRANSFER', 'تحويل / Transfer')], default='CASH', max_length=20, verbose_name='طريقة الدفع / Payment Method'),
        ),
    ]
