# Generated by Django 5.0.6 on 2025-10-01 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_options_alter_accountingperiod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountrule',
            name='ar_account',
        ),
        migrations.RemoveField(
            model_name='discountrule',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='discountrule',
            name='is_withdrawn',
        ),
        migrations.RemoveField(
            model_name='discountrule',
            name='opened_journal_entry',
        ),
        migrations.RemoveField(
            model_name='discountrule',
            name='rev_account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account', verbose_name='الحساب / Account'),
        ),
        migrations.DeleteModel(
            name='StudentWithdrawal',
        ),
    ]
