# Generated by Django 5.0.6 on 2025-10-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_discountrule_ar_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expenseentry',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='expenseentry',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='expenseentry',
            name='vendor',
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
