# Generated by Django 5.0.6 on 2025-10-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_expenseentry_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseentry',
            name='receipt_number',
        ),
    ]
