# Generated by Django 5.0.6 on 2025-10-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_expenseentry_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='annual_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الميزانية السنوية / Annual Budget'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='cost_center_type',
            field=models.CharField(choices=[('ACADEMIC', 'أكاديمي / Academic'), ('ADMINISTRATIVE', 'إداري / Administrative'), ('OPERATIONAL', 'تشغيلي / Operational'), ('SUPPORT', 'دعم / Support')], default='ACADEMIC', max_length=20, verbose_name='نوع مركز التكلفة / Cost Center Type'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المدير / Manager Name'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف المدير / Manager Phone'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الميزانية الشهرية / Monthly Budget'),
        ),
    ]
