# Generated by Django 5.0.6 on 2025-10-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_costcenter_annual_budget_costcenter_cost_center_type_and_more'),
        ('employ', '0005_alter_employeepermission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.costcenter', verbose_name='مركز التكلفة / Cost Center'),
        ),
        migrations.CreateModel(
            name='CourseTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية / Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية / End Date')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='أجر الساعة / Hourly Rate')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب الشهري / Monthly Rate')),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي الساعات / Total Hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط / Active')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course', verbose_name='الدورة / Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employ.teacher', verbose_name='المدرس / Teacher')),
            ],
            options={
                'verbose_name': 'تعيين مدرس للدورة / Course Teacher Assignment',
                'verbose_name_plural': 'تعيينات المدرسين للدورات / Course Teacher Assignments',
                'unique_together': {('course', 'teacher', 'start_date')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_courses', through='accounts.CourseTeacherAssignment', to='employ.teacher', verbose_name='المدرسون المعينون / Assigned Teachers'),
        ),
    ]
